replicaCount: 2

image:
  repository: nginx
  tag: "1.30.4-alpine3.24"
  pullPolicy: IfNotPresent

appVersion: "1.0.0"
nameOverride: ""
fullnameOverride: "api-gateway"

containerPort: 80

service:
  type: LoadBalancer
  port: 80
  annotations: {}
  loadBalancerIP: ""

health:
  path: /gateway-health
  readinessInitialDelaySeconds: 3
  livenessInitialDelaySeconds: 10

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
